### PR TITLE
Walletd issues

### PR DESCRIPTION
**Pull request by dbileck**
This resolves a few issues noticed communicating with walletd:
- If an existing wallet daemon was running, it would fail to connect to it because the rpc password is different. So now always terminate any existing wallet daemon.
- The known block count occasionally temporarily drops (no idea why, potential walletd issue?). If it drops below the block count, the wallet may open before it has finished synchronizing. Prevent the wallet from opening prematurely.
- Add error handling in case RPC server is not running when stopping wallet daemon. When stopping the wallet daemon, it first attempts to save the wallet. However, the daemon may not be running/communicating.
- Wait for RPC server to start after launching wallet daemon. When first launching the wallet daemon, it may take some time before the RPC server is running. Previously, we would timeout and eventually quit if it took too long, which would occur if it was importing blocks from blockchain storage.

### CODE REVIEW

**Comment by CaptainMeatloaf** [comment]
Perhaps it could be worth a look into using the `subprocess` module: https://docs.python.org/2.7/library/subprocess.html

**Comment by fexra** [comment]
I'm not sure if it would be a good idea to **always** terminate any exisiting walletd daemon. As an app developer who is building a web wallet around the walletd that makes me sweat. To my understanding, you can only run one walletd process per port. Why not just change the port, if there is already an existing daemon running? Or at least set a warning.

**Comment by fexra** [comment]
I'm not sure if it would be a good idea to always terminate any exisiting walletd daemon. To my understanding, you can only run one walletd process per port. Why not just change the port, if there is already an existing daemon running? Or at least set a warning.

**Comment by dbileck** [comment]
@CaptainMeatloaf it already utilizes subprocess.popen. Is there something specific you had in mind?

**Comment by dbileck** [comment]
@fexra good point. This approach is a little aggressive. I was trying to make it a little more  user friendly rather than spitting out an error and leave it to the user to kill the process. But I will look into launching another process and using a different port. If not will spit out a better error.

**Comment by fexra** [comment]
@dbileck I think that is the way to go. I'm currently building apps on top of the walletd daemon locally, and with your current fix I wouldn't be able to run the python-wallet and another walletd for development or even for something else like woo-turtle. Definitely use another port :)

**Comment by dbileck** [comment]
I have reverted my change so now it no longer terminates the daemon. In the end I decided to just exit if another daemon is running because even if I were to launch another daemon using a different port, would still need to consider using a different p2p network port and a different payment service port as well. In addition, would also need to consider database conflicts and would have to chose a different data directory, which not sure we would want to store another database.

**Pull request merged**
